export type Station = {
  id: string;
  name: string;
};

export type MetroLine = {
  lineId: string;
  lineNumber: number | string;
  lineColor: string;
  lineName: string;
  stations: Station[];
};

export const metroLines: MetroLine[] = [
  {
    lineId: '1',
    lineNumber: 1,
    lineColor: '#1E88E5',
    lineName: 'Línea 1',
    stations: [
      { id: '1-1', name: 'Pinar de Chamartín' },
      { id: '1-2', name: 'Colombia' },
      { id: '1-3', name: 'Concha Espina' },
      { id: '1-4', name: 'Cruz del Rayo' },
      { id: '1-5', name: 'Núñez de Balboa' },
      { id: '1-6', name: 'Diego de León' },
      { id: '1-7', name: 'Lista' },
      { id: '1-8', name: 'Goya' },
      { id: '1-9', name: 'Velázquez' },
      { id: '1-10', name: 'Serrano' },
      { id: '1-11', name: 'Colón' },
      { id: '1-12', name: 'Banco de España' },
      { id: '1-13', name: 'Sevilla' },
      { id: '1-14', name: 'Sol' },
      { id: '1-15', name: 'Tirso de Molina' },
      { id: '1-16', name: 'Antón Martín' },
      { id: '1-17', name: 'Atocha' },
      { id: '1-18', name: 'Palos de la Frontera' },
      { id: '1-19', name: 'Delicias' },
      { id: '1-20', name: 'Legazpi' },
      { id: '1-21', name: 'Usera' },
      { id: '1-22', name: 'Pradolongo' },
      { id: '1-23', name: 'Puente de Vallecas' },
      { id: '1-24', name: 'Nueva Numancia' },
      { id: '1-25', name: 'Portazgo' },
      { id: '1-26', name: 'Buenos Aires' },
      { id: '1-27', name: 'San Fermín / Orcasur' },
      { id: '1-28', name: 'El Caño Roto' },
      { id: '1-29', name: 'Pan Bendito' },
      { id: '1-30', name: 'La Peseta' },
      { id: '1-31', name: 'Aluche' },
      { id: '1-32', name: 'Empalme' },
      { id: '1-33', name: 'Valdecarros' },
    ],
  },
  {
    lineId: '2',
    lineNumber: 2,
    lineColor: '#E53935',
    lineName: 'Línea 2',
    stations: [
      { id: '2-1', name: 'Cuatro Caminos' },
      { id: '2-2', name: 'Quevedo' },
      { id: '2-3', name: 'San Bernardo' },
      { id: '2-4', name: 'Noviciado' },
      { id: '2-5', name: 'Santo Domingo' },
      { id: '2-6', name: 'Ópera' },
      { id: '2-7', name: 'Sevilla' },
      { id: '2-8', name: 'Banco de España' },
      { id: '2-9', name: 'Retiro' },
      { id: '2-10', name: 'Príncipe de Vergara' },
      { id: '2-11', name: 'Goya' },
      { id: '2-12', name: 'Manuel Becerra' },
      { id: '2-13', name: 'Ventas' },
      { id: '2-14', name: 'Estrella' },
      { id: '2-15', name: 'Vinateros' },
      { id: '2-16', name: 'Artilleros' },
      { id: '2-17', name: 'Alsacia' },
      { id: '2-18', name: 'Las Rosas' },
    ],
  },
  {
    lineId: '3',
    lineNumber: 3,
    lineColor: '#FDD835',
    lineName: 'Línea 3',
    stations: [
      { id: '3-1', name: 'Villaverde Alto' },
      { id: '3-2', name: 'Villaverde Bajo / Cruce' },
      { id: '3-3', name: 'Legazpi' },
      { id: '3-4', name: 'Delicias' },
      { id: '3-5', name: 'Palos de la Frontera' },
      { id: '3-6', name: 'Embajadores' },
      { id: '3-7', name: 'Lavapiés' },
      { id: '3-8', name: 'Sol' },
      { id: '3-9', name: 'Callao' },
      { id: '3-10', name: 'Ventura Rodríguez' },
      { id: '3-11', name: 'Argüelles' },
      { id: '3-12', name: 'Moncloa' },
    ],
  },
  {
    lineId: '4',
    lineNumber: 4,
    lineColor: '#6D4C41',
    lineName: 'Línea 4',
    stations: [
      { id: '4-1', name: 'Argüelles' },
      { id: '4-2', name: 'Alonso Martínez' },
      { id: '4-3', name: 'Colón' },
      { id: '4-4', name: 'Serrano' },
      { id: '4-5', name: 'Diego de León' },
      { id: '4-6', name: 'Avda. de la Paz' },
      { id: '4-7', name: 'Arturo Soria' },
      { id: '4-8', name: 'Esperanza' },
      { id: '4-9', name: 'Mar de Cristal' },
      { id: '4-10', name: 'Canillas' },
      { id: '4-11', name: 'Hortaleza' },
      { id: '4-12', name: 'Pinar de Chamartín' },
    ],
  },
  {
    lineId: '5',
    lineNumber: 5,
    lineColor: '#43A047',
    lineName: 'Línea 5',
    stations: [
      { id: '5-1', name: 'Alameda de Osuna' },
      { id: '5-2', name: 'Canillejas' },
      { id: '5-3', name: 'Torre Arias' },
      { id: '5-4', name: 'Suanzes' },
      { id: '5-5', name: 'Ciudad Lineal' },
      { id: '5-6', name: 'Quintana' },
      { id: '5-7', name: 'El Carmen' },
      { id: '5-8', name: 'Ventas' },
      { id: '5-9', name: 'Diego de León' },
      { id: '5-10', name: 'Núñez de Balboa' },
      { id: '5-11', name: 'Rubén Darío' },
      { id: '5-12', name: 'Alonso Martínez' },
      { id: '5-13', name: 'Chueca' },
      { id: '5-14', name: 'Gran Vía' },
      { id: '5-15', name: 'Callao' },
      { id: '5-16', name: 'Ópera' },
      { id: '5-17', name: 'La Latina' },
      { id: '5-18', name: 'Puerta de Toledo' },
      { id: '5-19', name: 'Acacias' },
      { id: '5-20', name: 'Pirámides' },
      { id: '5-21', name: 'Marqués de Vadillo' },
      { id: '5-22', name: 'Urgel' },
      { id: '5-23', name: 'Oporto' },
      { id: '5-24', name: 'Vista Alegre' },
      { id: '5-25', name: 'Carabanchel' },
      { id: '5-26', name: 'Eugenia de Montijo' },
      { id: '5-27', name: 'Empalme' },
      { id: '5-28', name: 'Alcorcón Central' },
      { id: '5-29', name: 'Leganés Central' },
    ],
  },
  {
    lineId: '6',
    lineNumber: 6,
    lineColor: '#757575',
    lineName: 'Línea 6',
    stations: [
      { id: '6-1', name: 'Laguna' },
      { id: '6-2', name: 'Carpetana' },
      { id: '6-3', name: 'Oporto' },
      { id: '6-4', name: 'Opañel' },
      { id: '6-5', name: 'Plaza Elíptica' },
      { id: '6-6', name: 'Legazpi' },
      { id: '6-7', name: 'Méndez Álvaro' },
      { id: '6-8', name: 'Pacífico' },
      { id: '6-9', name: 'Conde de Casal' },
      { id: '6-10', name: "Doctor Marañón" },
      { id: '6-11', name: "O'Donnell" },
      { id: '6-12', name: 'Manuel Becerra' },
      { id: '6-13', name: 'Sainz de Baranda' },
      { id: '6-14', name: 'Diego de León' },
      { id: '6-15', name: 'Avenida de América' },
      { id: '6-16', name: 'Nuevos Ministerios' },
      { id: '6-17', name: 'Cuatro Caminos' },
      { id: '6-18', name: 'Metropolitano' },
      { id: '6-19', name: 'Ciudad Universitaria' },
      { id: '6-20', name: 'Moncloa' },
      { id: '6-21', name: 'Argüelles' },
      { id: '6-22', name: 'Príncipe Pío' },
      { id: '6-23', name: 'Puerta del Ángel' },
    ],
  },
  {
    lineId: '7',
    lineNumber: 7,
    lineColor: '#FF8F00',
    lineName: 'Línea 7',
    stations: [
      { id: '7-1', name: 'Hospital del Henares' },
      { id: '7-2', name: 'Henares' },
      { id: '7-3', name: 'San Fernando' },
      { id: '7-4', name: 'Jarama' },
      { id: '7-5', name: 'Coslada Central' },
      { id: '7-6', name: 'La Rambla' },
      { id: '7-7', name: 'Estadio Metropolitano' },
      { id: '7-8', name: 'Las Musas' },
      { id: '7-9', name: 'Barajas' },
      { id: '7-10', name: 'Aeropuerto T1-T2-T3' },
      { id: '7-11', name: 'Aeropuerto T4' },
      { id: '7-12', name: 'Campo de las Naciones' },
      { id: '7-13', name: 'Canillejas' },
      { id: '7-14', name: 'Avenida de América' },
      { id: '7-15', name: 'Cartagena' },
      { id: '7-16', name: 'Prosperidad' },
      { id: '7-17', name: 'Alfonso XIII' },
      { id: '7-18', name: 'Avda. de la Paz' },
      { id: '7-19', name: 'Valdezarza' },
      { id: '7-20', name: 'Pitis' },
    ],
  },
  {
    lineId: '8',
    lineNumber: 8,
    lineColor: '#E91E8C',
    lineName: 'Línea 8',
    stations: [
      { id: '8-1', name: 'Nuevos Ministerios' },
      { id: '8-2', name: 'Colombia' },
      { id: '8-3', name: 'Pinar del Rey' },
      { id: '8-4', name: 'Mar de Cristal' },
      { id: '8-5', name: 'Aeropuerto T1-T2-T3' },
      { id: '8-6', name: 'Aeropuerto T4' },
    ],
  },
  {
    lineId: '9',
    lineNumber: 9,
    lineColor: '#6A1B9A',
    lineName: 'Línea 9',
    stations: [
      { id: '9-1', name: 'Arganda del Rey' },
      { id: '9-2', name: 'La Poveda' },
      { id: '9-3', name: 'Rivas Urbanizaciones' },
      { id: '9-4', name: 'Rivas Vaciamadrid' },
      { id: '9-5', name: 'Vicálvaro' },
      { id: '9-6', name: 'Valdebernardo' },
      { id: '9-7', name: 'Barrio de la Concepción' },
      { id: '9-8', name: 'Artilleros' },
      { id: '9-9', name: 'Pavones' },
      { id: '9-10', name: 'Vinateros' },
      { id: '9-11', name: 'Estrella' },
      { id: '9-12', name: 'Conde de Casal' },
      { id: '9-13', name: 'Pacífico' },
      { id: '9-14', name: 'Atocha Renfe' },
      { id: '9-15', name: 'Nuevos Ministerios' },
      { id: '9-16', name: 'Plaza de Castilla' },
      { id: '9-17', name: 'Paco de Lucía' },
    ],
  },
  {
    lineId: '10',
    lineNumber: 10,
    lineColor: '#0D47A1',
    lineName: 'Línea 10',
    stations: [
      { id: '10-1', name: 'Tres Olivos' },
      { id: '10-2', name: 'Montecarmelo' },
      { id: '10-3', name: 'Las Tablas' },
      { id: '10-4', name: 'La Granja' },
      { id: '10-5', name: 'Ronda de la Comunicación' },
      { id: '10-6', name: 'Hospital Infanta Sofía' },
      { id: '10-7', name: 'Fuencarral' },
      { id: '10-8', name: 'Begoña' },
      { id: '10-9', name: 'Plaza de Castilla' },
      { id: '10-10', name: 'Cuzco' },
      { id: '10-11', name: 'Santiago Bernabéu' },
      { id: '10-12', name: 'Nuevos Ministerios' },
      { id: '10-13', name: 'Tribunal' },
      { id: '10-14', name: 'Alonso Martínez' },
      { id: '10-15', name: 'Gregorio Marañón' },
      { id: '10-16', name: 'Príncipe de Vergara' },
      { id: '10-17', name: 'Avenida de América' },
      { id: '10-18', name: 'Laguna' },
      { id: '10-19', name: 'Empalme' },
    ],
  },
  {
    lineId: '11',
    lineNumber: 11,
    lineColor: '#558B2F',
    lineName: 'Línea 11',
    stations: [
      { id: '11-1', name: 'Plaza Elíptica' },
      { id: '11-2', name: 'Pradolongo' },
      { id: '11-3', name: 'Moscardó' },
      { id: '11-4', name: 'Marqués de Vadillo' },
      { id: '11-5', name: 'La Fortuna' },
    ],
  },
  {
    lineId: '12',
    lineNumber: 12,
    lineColor: '#9E9D24',
    lineName: 'Línea 12',
    stations: [
      { id: '12-1', name: 'Puerta del Sur' },
      { id: '12-2', name: 'Juan de la Cierva' },
      { id: '12-3', name: 'Getafe Central' },
      { id: '12-4', name: 'El Casar' },
      { id: '12-5', name: 'Los Espartales' },
      { id: '12-6', name: 'Hospital de Getafe' },
      { id: '12-7', name: 'Alonso de Mendoza' },
      { id: '12-8', name: 'Leganés Central' },
      { id: '12-9', name: 'Conservatorio' },
      { id: '12-10', name: 'Julián Besteiro' },
      { id: '12-11', name: 'San Nicasio' },
      { id: '12-12', name: 'Alcorcón Central' },
      { id: '12-13', name: 'Parque de Lisboa' },
      { id: '12-14', name: 'Hospital de Fuenlabrada' },
      { id: '12-15', name: 'Loranca' },
      { id: '12-16', name: 'Fuenlabrada Central' },
      { id: '12-17', name: 'La Peseta' },
      { id: '12-18', name: 'Móstoles Central' },
    ],
  },
  {
    lineId: 'R',
    lineNumber: 'R',
    lineColor: '#1E88E5',
    lineName: 'Ramal',
    stations: [
      { id: 'R-1', name: 'Ópera' },
      { id: 'R-2', name: 'Príncipe Pío' },
    ],
  },
];

export const stationsByLineId = Object.fromEntries(
  metroLines.map((line) => [line.lineId, line.stations])
);
